Dzwelling/close toast after five seconds
AlaskaAirlines/auro-toast pull request #18
Opened 2023-05-30 21:25 UTC by DZwell

# Alaska Airlines Pull Request

**Fixes:** #13 

## Summary:

Automatically close the toast after 5 seconds have elapsed.

## Type of change:

- [x] New capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-06-01 20:23 UTC, blackfalcon requested changes

2023-06-01 20:23 UTC, blackfalcon commented on src/auro-toast.js
> +const FIVE_SECONDS = 5000;
I wouldn't make this so absolute. How about... 

```
const TIME_DELAY = 5000;
```

2023-06-02 17:58 UTC, blackfalcon approved these changes
This update is APPROVED, but please amend that last commit to the primary commit. Also, changing that value is not a `chore` but a `refactor`. But please amend it as this is not of real value in the overall history. 

Thanks!

2023-06-05 16:27 UTC, DZwell commented
@blackfalcon I pushed new changes if you'd like to take another look.

2023-06-05 20:53 UTC, blackfalcon approved these changes

2023-06-05 21:10 UTC, merged