Update CSS token per new design system theming capability
AlaskaAirlines/auro-toast pull request #30
Opened 2023-11-08 10:55 UTC by irma-kurnia-alaska

# Alaska Airlines Pull Request

**Fixes:** #29 

## Summary:

- Update the design tokens to reflect the new theming conventions regarding tokens from the AuroDesignTokens and JetstreamDesignTokens repo.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-08 17:27 UTC, jason-capsule42 approved these changes, later dismissed

2023-11-10 04:02 UTC, blackfalcon requested changes
Please update all npm dependencies and update repo to support Node support policy https://auro.alaskaair.com/node-support#gsc.tab=0

2023-11-10 04:02 UTC, blackfalcon commented on demo/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@aurodesignsystem/design-tokens@latest/dist/tokens/CSSCustomProperties.css">
Please update to mirror this code 

https://github.com/AlaskaAirlines/auro-avatar/blob/main/demo/index.html#L12-L17

2023-11-10 04:02 UTC, blackfalcon commented on package.json
>      "@alaskaairux/design-tokens": "^3.13.0",
Remove legacy package reference

2023-11-10 04:02 UTC, blackfalcon commented on package.json
>      "@alaskaairux/design-tokens": "^3.14.0",
Remove legacy package reference

2023-11-10 04:02 UTC, blackfalcon commented on src/style-toaster.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SassCustomProperties';
```suggestion
```

2023-11-10 04:02 UTC, blackfalcon commented on src/style-toaster.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables.scss';
```suggestion
```

Remove duplicate reference

2023-11-10 04:02 UTC, blackfalcon commented on src/style.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SassCustomProperties';
```suggestion
```

2023-11-10 04:02 UTC, blackfalcon commented on src/style.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SCSSVariables.scss';
```suggestion
```

2023-11-10 04:15 UTC, irma-kurnia-alaska commented on demo/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@aurodesignsystem/design-tokens@latest/dist/tokens/CSSCustomProperties.css">
ok, sure. thank you.

2023-11-16 12:39 UTC, merged

2023-11-16 12:42 UTC, blackfalcon commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-toast/v/1.0.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-toast/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: